{% set name = "types-click" %}
{% set version = "7.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-click-{{ version }}.tar.gz
  sha256: b6604968be6401dc516311ca50708a0a28baa7a0cb840efd7412f0dbbff4e092

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/click-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for click
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
